# Generated by Django 3.1.14 on 2022-06-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveSmallIntegerField(verbose_name='Порядковый номер')),
                ('order_number', models.PositiveIntegerField(verbose_name='Номер заказа')),
                ('dollar_value', models.PositiveIntegerField(verbose_name='Стоимость в долларах')),
                ('rub_value', models.FloatField(verbose_name='Стоимость в рублях')),
                ('delivery_date', models.DateField(verbose_name='Срок поставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['serial_number'],
            },
        ),
    ]
