# Generated by Django 3.1.14 on 2022-06-18 10:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsorder',
            name='recalculation_date',
            field=models.DateField(default=datetime.datetime(2005, 12, 5, 0, 0), verbose_name='Дата пересчета заказа в рубли'),
            preserve_default=False,
        ),
    ]
