# Generated by Django 3.1.14 on 2022-06-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_goodsorder_recalculation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsorder',
            name='recalculation_date',
        ),
    ]
