# Generated by Django 3.1.14 on 2022-06-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_goodsorder_recalculation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsorder',
            name='is_sending',
            field=models.BooleanField(default=False, verbose_name='Статус отправки увдомлением в телеграмм'),
        ),
    ]
